global:
  scrape_interval: 15s  # С какой периодичностью собирать метрики.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'  # Добавление cAdvisor
    static_configs:
      - targets: [ 'cadvisor:8080' ]
