name: Deploy to Server

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Disable Host Key Checking
      run: |
        mkdir -p ~/.ssh
        echo "Host ${{ secrets.SERVER_IP }}" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

    - name: Deploy to Server
      run: ssh root@${{ secrets.SERVER_IP }} 'bash -s' < deploy_script.sh

  deploy-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.IFT_DEPLOY_KEY }}

    - name: Disable Host Key Checking
      run: |
        mkdir -p ~/.ssh
        echo "Host ${{ secrets.IFT_SERVER_IP }}" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

    - name: Deploy to Server
      run: ssh root@${{ secrets.IFT_SERVER_IP }} 'bash -s' < deploy_script.sh
